name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app

            git pull origin main

            docker stop flask-app || true
            docker rm flask-app || true

            docker build -t flask-app .

            docker run -d -p 8000:8000 \
            -e OLLAMA_HOST=${{ secrets.OLLAMA_HOST }} \
            flask-app